# Generated by Django 6.0.7 on 2026-09-08 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Savatcha',
                'verbose_name_plural': 'Savatchalar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Buyurtma raqami')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlandi'), ('shipping', 'Yetkazib berilmoqda'), ('delivered', 'Yetkazib berildi'), ('cancelled', 'Bekor qilindi'), ('returned', 'Qaytarildi')], default='new', max_length=20, verbose_name='Holati')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Umumiy summa (Snapshot)')),
                ('address', models.CharField(max_length=255, verbose_name='Yetkazib berish manzili')),
                ('contact_phone', models.CharField(max_length=13, verbose_name='Aloqa telefoni')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotib olingan narx (Snapshot)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Jami summa (Snapshot)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma mahsuloti',
                'verbose_name_plural': 'Buyurtma mahsulotlari',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlandi'), ('shipping', 'Yetkazib berilmoqda'), ('delivered', 'Yetkazib berildi'), ('cancelled', 'Bekor qilindi'), ('returned', 'Qaytarildi')], max_length=20, null=True, verbose_name='Eski holati')),
                ('to_status', models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlandi'), ('shipping', 'Yetkazib berilmoqda'), ('delivered', 'Yetkazib berildi'), ('cancelled', 'Bekor qilindi'), ('returned', 'Qaytarildi')], max_length=20, verbose_name='Yangi holati')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh/Sabab')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="O'zgartiruvchi xodim")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='order.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma statusi tarixi',
                'verbose_name_plural': 'Buyurtma statuslari tarixi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Qaytarilayotgan miqdor')),
                ('reason', models.TextField(verbose_name='Qaytarish sababi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name="So'rov holati")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='order.orderitem', verbose_name='Buyurtma mahsuloti')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiqqan xodim")),
            ],
            options={
                'verbose_name': 'Qaytarilgan mahsulot',
                'verbose_name_plural': 'Qaytarilgan mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Miqdori')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.cart', verbose_name='Savatcha')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Savatchadagi mahsulot',
                'verbose_name_plural': 'Savatchadagi mahsulotlar',
                'unique_together': {('cart', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='order_order_order_n_fb1851_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='order_order_user_id_f784ac_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='order_order_status_b4d09f_idx'),
        ),
    ]
